services:
  - type: web
    name: peakperformance
    runtime: static
    buildCommand: ""
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /forms/embed.js
        destination: https://ownet.opticwise.com/forms/embed.js
      - type: rewrite
        source: /api/public/forms/*
        destination: https://ownet.opticwise.com/api/public/forms/:splat
